name: Deploy Backend and Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy Backend (Docker)
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER_API: ${{ secrets.DEPLOY_USER_API }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER_API@$DEPLOY_HOST \
            "cd /home/uatts-api/htdocs/api.uatts.site && docker compose --env-file .env -f docker-compose.cloudpanel.yml build --pull && docker compose --env-file .env -f docker-compose.cloudpanel.yml up -d"
      - name: Deploy Frontend (Vite)
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER_FRONT: ${{ secrets.DEPLOY_USER_FRONT }}
          FRONT_DEST: ${{ secrets.FRONT_DEST }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: |
          npm ci
          npm run build -- --mode production
          rsync -avz --delete dist/ $DEPLOY_USER_FRONT@$DEPLOY_HOST:$FRONT_DEST
